# Generated by Django 5.2.7 on 2025-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
