# Generated by Django 5.2.7 on 2025-10-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sponsor_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='payment_amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
