# Generated by Django 5.2.7 on 2025-10-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sponsor_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='sum',
        ),
    ]
