# Generated by Django 5.2.7 on 2025-10-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_sponsor_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contract_amount',
            new_name='allocated_amount',
        ),
    ]
