# Generated by Django 5.2.7 on 2025-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_contract_amount_student_allocated_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contract_amount',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
