# Generated by Django 5.2.7 on 2025-10-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_contract_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_at',
            field=models.DateTimeField(auto_now=True, null=None),
        ),
    ]
