# Generated by Django 5.2.7 on 2025-10-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
